CREATE DATABASE SOCIETY_SPHERE;
USE SOCIETY_SPHERE;

CREATE TABLE STUDENT_DETAIL
(ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(45) NOT NULL,
STATUS VARCHAR (10) NOT NULL);

CREATE TABLE COLLEGE_ADMIN_DETAIL
(ID INT PRIMARY KEY AUTO_INCREMENT,
ADMIN_NAME VARCHAR(50) NOT NULL,
ADMIN_EMAIL VARCHAR(50) NOT NULL);



